spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/organicare
#    username: postgres
#    password: tadiewa


  datasource:
    url: jdbc:postgresql://dpg-d38gecvdiees73cijjd0-a.oregon-postgres.render.com:5432/organicare_cstv
    username: tadiewa
    password: HmTH8KmpOg8BfMXnmOGuUr3dzMffwqrJ



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-bean-definition-overriding: true



server:
  port: 9033


application:
  security:
    jwt:
      secret-key: DRo3wXPnHyBb+1KXVID6x69oDg4IPi4CnmViCaENw2M=
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
